version: "2"
run:
  tests: true
linters:
  enable:
    - contextcheck
    - goconst
    - gocritic
    - gocyclo
    - nakedret
    - prealloc
    - rowserrcheck
    - sloglint
    - sqlclosecheck
    - unconvert
    - unparam
  settings:
    errcheck:
      check-blank: true
    funlen:
      lines: 80
      statements: 50
    gocognit:
      min-complexity: 30
    gocyclo:
      min-complexity: 20
    govet:
      enable:
        - shadow
    nakedret:
      max-func-lines: 50
    staticcheck:
      checks:
        - -QF1001
        - -SA2002
        - -SA6000
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: api
      - path: (.+)\.go$
        text: internal/dto
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
