version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - govet
    - ineffassign
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused
    - sqlclosecheck
    - rowserrcheck
    - contextcheck
    - sloglint

  settings:
    errcheck:
      check-blank: true
    gocyclo:
      min-complexity: 20
    govet:
      enable:
        - shadow
    funlen:
      lines: 80
      statements: 50
    gocognit:
      min-complexity: 30
    nakedret:
      max-func-lines: 50
    staticcheck:
      checks:
        - all
        - "-SA6000"
        - "-QF1001"
        - "-SA2002"

issues:
  exclude:
    - path: api/**/*
    - path: internal/dto/**/*
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  exclusions:
    generated: lax